GET http://localhost:3001/todos

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "hi",
		"todo": "lol",
		"dueDate": "22/12/2024",
		"priority": "medium"
}

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "testing again",
		"todo": "test",
		"dueDate": "",
		"priority": "none"
}

###
// do GET request and take an ID from there first
DELETE http://localhost:3001/todos/668bdb108c3a8788c1b4b923

###

PUT http://localhost:3001/todos/668be0fde340448a748d54dc
Content-Type: application/json

{
		"title": "Updating Todo!",
		"todo": "Updated Todo",
		"dueDate": "",
		"priority": "high"
}