GET http://localhost:3001/todos

###

POST http://localhost:3001/todos
Content-Type: application/json

{
		"todo": "test3",
		"important": true
}

###
// do GET request and take an ID from there first
DELETE http://localhost:3001/todos/667ecffc4d1f25bf44236377

###

PUT http://localhost:3001/todos/667ecffd4d1f25bf44236379
Content-Type: application/json

{
		"todo": "Updated Todo",
		"important": true
}