GET http://localhost:3001/todos

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "test user",
		"todo": "user",
		"dueDate": "2024-05-24",
		"priority": "medium",
		"project": "",
		"id": "66ec7fddc0d3c218209e9441"
}

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "testing user with project called 'school'",
		"todo": "test",
		"dueDate": "",
		"priority": "none",
		"project": "6695c05c1889af8a171b2dd7",
		"id": "66ec7fddc0d3c218209e9441"
}

###
// do GET request and take an ID from there first
DELETE http://localhost:3001/todos/6695cdb29e6a2fca27344ada

###

PUT http://localhost:3001/todos/668be0fde340448a748d54dc
Content-Type: application/json

{
		"title": "Updating Todo!",
		"todo": "Updated Todo",
		"dueDate": "",
		"priority": "high"
}