GET http://localhost:3001/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOiI2NzI2NmM1ZDJmNWZmNGZjYTc0NjQ2NjQiLCJpYXQiOjE3MzA1NzU0MjZ9.gIdBroWOm3BjsSx6pJAWGXqmf8TLDkeRgfSZdwaCvUY

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "test user",
		"todo": "user",
		"dueDate": "2024-05-24",
		"priority": "medium",
		"project": "",
		"id": "66ec7fddc0d3c218209e9441"
}

###
// BEARER IS TOKEN

POST http://localhost:3001/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOiI2NzI2NmM1ZDJmNWZmNGZjYTc0NjQ2NjQiLCJpYXQiOjE3MzA1NzU0MjZ9.gIdBroWOm3BjsSx6pJAWGXqmf8TLDkeRgfSZdwaCvUY

{		
		"title": "testing email login!'",
		"todo": "test",
		"dueDate": "2025-08-08",
		"priority": "none",
		"project": "",
		"id": "66fcba84537d9a28cc194d48"
}

###
// do GET request and take an ID from there first
DELETE http://localhost:3001/todos/6695cdb29e6a2fca27344ada

###

PUT http://localhost:3001/todos/66f3246142ec7f5ae30fe585
Content-Type: application/json

{
		"title": "Updating Todo Testing User!",
		"todo": "Updated Todo",
		"dueDate": "",
		"priority": "high"
}