GET http://localhost:3001/todos

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "test date again",
		"todo": "yay",
		"dueDate": "2024-05-24",
		"priority": "medium"
}

###

POST http://localhost:3001/todos
Content-Type: application/json

{		
		"title": "testing project",
		"todo": "test",
		"dueDate": "",
		"priority": "none",
		"project": "6695c05c1889af8a171b2dd7"
}

###
// do GET request and take an ID from there first
DELETE http://localhost:3001/todos/6695cdb29e6a2fca27344ada

###

PUT http://localhost:3001/todos/668be0fde340448a748d54dc
Content-Type: application/json

{
		"title": "Updating Todo!",
		"todo": "Updated Todo",
		"dueDate": "",
		"priority": "high"
}