GET http://localhost:3001/users

###
POST http://localhost:3001/users
Content-Type: application/json

{
    "username": "test",
    "name": "Supertest",
    "password": "testing"
}

###
POST http://localhost:3001/users
Content-Type: application/json

{
    "username": "to delete",
    "name": "Deleting!",
    "password": "delete"
}

###
DELETE http://localhost:3001/users/66f3330df54673089338addf
