name: Test Backend

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}

    steps:
      - uses: actions/checkout@v3 # Update to the latest version supporting Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Update to the latest version supporting Node.js 20
        with:
          node-version: '20'

      #   - name: Change Directory to Backend
      #     run: cd server

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./server

      - name: Compile TypeScript (Backend)
        run: npm run tsc
        working-directory: ./server

      - name: Test Backend code
        run: npm run test
        working-directory: ./server
        env:
          NODE_ENV: test

      - name: Lint Backend code
        run: npm run lint
        working-directory: ./server

        # - name: Build Project (Frontend)
        #   run: |
        #     cd client
        #     npm install
        #     npm run build
