name: Test Backend

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Update to the latest version supporting Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Update to the latest version supporting Node.js 20
        with:
          node-version: '20'

      - name: Change Directory to Backend
        run: cd server

      - name: Install Backend Dependencies
        run: npm ci

      - name: Compile TypeScript (Backend)
        run: npm run tsc

      - name: Test Backend code
        run: npm run test

      - name: Lint Backend code
        run: npm run lint

        # - name: Build Project (Frontend)
        #   run: |
        #     cd frontend
        #     npm ci
        #     npm run build
